<wsdl:definitions
     name="pollForClosedProposals"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProcessArtistProposals/ProposalClosure/pollForClosedProposals"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProcessArtistProposals/ProposalClosure/pollForClosedProposals"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/pollForClosedProposals"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="pollForClosedProposals_plt" >
    <plt:role name="pollForClosedProposals_role" >
      <plt:portType name="tns:pollForClosedProposals_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/pollForClosedProposals" schemaLocation="../Schemas/pollForClosedProposals_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ProposedActsCollection_msg">
        <wsdl:part name="ProposedActsCollection" element="top:ProposedActsCollection"/>
    </wsdl:message>
    <wsdl:portType name="pollForClosedProposals_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:ProposedActsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
