<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ArtistsForEvents/SubmitArtistProposalForEvent/initializeArtistProposal" name="initializeArtistProposal-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="initializeArtistProposal.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ArtistsForEvents/SubmitArtistProposalForEvent/initializeArtistProposal"/>
    <wsdl:binding name="initializeArtistProposal_ptt-binding" type="init:initializeArtistProposal_ptt" xmlns:init="http://xmlns.oracle.com/pcbpel/adapter/db/ArtistsForEvents/SubmitArtistProposalForEvent/initializeArtistProposal">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="initializeArtistProposal">
            <soap:operation soapAction="initializeArtistProposal"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>