<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://TargetNamespace.com/SubmitArtistProposalService_Operation1_request"
                xmlns:ns0="valencia.insight.demo" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="ProposeArtistService.xsd"/>
        <oracle-xsl-mapper:rootElement name="proposal" namespace="valencia.insight.demo"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="nxsd_json-artistProposal.xsd"/>
        <oracle-xsl-mapper:rootElement name="proposal"
                                       namespace="http://TargetNamespace.com/SubmitArtistProposalService_Operation1_request"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI MAR 11 17:18:13 CET 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:proposal>
      <tns:proposedAct>
        <tns:artist>
          <xsl:value-of select="/ns0:proposal/ns0:proposedAct/ns0:artist"/>
        </tns:artist>
        <tns:event>
          <xsl:value-of select="/ns0:proposal/ns0:proposedAct/ns0:event"/>
        </tns:event>
        <tns:numberOfVotes>
          <xsl:value-of select="/ns0:proposal/ns0:proposedAct/ns0:numberOfVotes"/>
        </tns:numberOfVotes>
        <tns:motivation>
          <xsl:value-of select="/ns0:proposal/ns0:proposedAct/ns0:motivation"/>
        </tns:motivation>
      </tns:proposedAct>
    </tns:proposal>
  </xsl:template>
</xsl:stylesheet>
