<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns0="http://TargetNamespace.com/SubmitArtistProposalService_Operation1_response"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:tns="valencia.insight.demo" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="nxsd_json-artistProposal-response.xsd"/>
        <oracle-xsl-mapper:rootElement name="actProposal-response"
                                       namespace="http://TargetNamespace.com/SubmitArtistProposalService_Operation1_response"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="ProposeArtistService.xsd"/>
        <oracle-xsl-mapper:rootElement name="proposalResponse" namespace="valencia.insight.demo"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI MAR 11 17:19:12 CET 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:proposalResponse>
      <tns:proposedActIdentifier>
        <xsl:value-of select="/ns0:actProposal-response/ns0:registeredActProposal/ns0:registrationId"/>
      </tns:proposedActIdentifier>
      <tns:artist>
        <xsl:value-of select="/ns0:actProposal-response/ns0:registeredActProposal/ns0:artist"/>
      </tns:artist>
      <tns:event>
        <xsl:value-of select="/ns0:actProposal-response/ns0:registeredActProposal/ns0:event"/>
      </tns:event>
      <tns:numberOfVotes>
        <xsl:value-of select="/ns0:actProposal-response/ns0:registeredActProposal/ns0:numberOfVotes"/>
      </tns:numberOfVotes>
      <tns:motivation>
        <xsl:value-of select="/ns0:actProposal-response/ns0:registeredActProposal/ns0:artist"/>
      </tns:motivation>
    </tns:proposalResponse>
  </xsl:template>
</xsl:stylesheet>
