<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="SendInArtistProposal"
     targetNamespace="http://oracle.com/sca/soapservice/SendInArtistProposal/SendInArtistProposal/SendInArtistProposal"
     xmlns:tns="http://oracle.com/sca/soapservice/SendInArtistProposal/SendInArtistProposal/SendInArtistProposal"
     xmlns:inp1="valencia.insight.demo"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="valencia.insight.demo" schemaLocation="../Schemas/ProposeArtistService.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part1" element="inp1:proposal"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="part1" element="inp1:proposalResponse"/>
    </wsdl:message>
    <wsdl:portType name="SendInArtistProposalService">
        <wsdl:operation name="sendInProposal">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
