<wsdl:definitions
     name="updateRejectedStatus"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProcessArtistProposals/JudgeArtistProposals/updateRejectedStatus"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProcessArtistProposals/JudgeArtistProposals/updateRejectedStatus"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/updateRejectedStatus"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="updateRejectedStatus_plt" >
    <plt:role name="updateRejectedStatus_role" >
      <plt:portType name="tns:updateRejectedStatus_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/updateRejectedStatus"
               schemaLocation="../Schemas/updateRejectedStatus_sp.xsd" />
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:portType name="updateRejectedStatus_ptt">
        <wsdl:operation name="updateRejectedStatus">
            <wsdl:input message="tns:args_in_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
