<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ProposalsService"
     targetNamespace="http://oracle.com/sca/soapservice/ProcessArtistProposals/NegotiateAndEngage/ProposalsService"
     xmlns:tns="http://oracle.com/sca/soapservice/ProcessArtistProposals/NegotiateAndEngage/ProposalsService"
     xmlns:inp1="valencia.insight.demo/negotiation"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="valencia.insight.demo/negotiation" schemaLocation="../Schemas/NegotiationService.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part1" element="inp1:eventIdentifier"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="part1" element="inp1:actProposalList"/>
    </wsdl:message>
    <wsdl:portType name="ProposalsService">
        <wsdl:operation name="findProposalsForEvent">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
