<wsdl:definitions
     name="retrieveProposalsForEvent"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProcessArtistProposals/NegotiateAndEngage/retrieveProposalsForEvent"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProcessArtistProposals/NegotiateAndEngage/retrieveProposalsForEvent"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/retrieveProposalsForEvent"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="retrieveProposalsForEvent_plt" >
    <plt:role name="retrieveProposalsForEvent_role" >
      <plt:portType name="tns:retrieveProposalsForEvent_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/retrieveProposalsForEvent" schemaLocation="../Schemas/retrieveProposalsForEvent_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="retrieveProposalsForEventSelect_inputParameters">
        <wsdl:part name="retrieveProposalsForEventSelect_inputParameters" element="top:retrieveProposalsForEventSelect_bEventInputParameters"/>
    </wsdl:message>
    <wsdl:message name="ProposedActsCollection_msg">
        <wsdl:part name="ProposedActsCollection" element="top:ProposedActsCollection"/>
    </wsdl:message>
    <wsdl:portType name="retrieveProposalsForEvent_ptt">
        <wsdl:operation name="retrieveProposalsForEventSelect">
            <wsdl:input message="tns:retrieveProposalsForEventSelect_inputParameters"/>
            <wsdl:output message="tns:ProposedActsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
