<wsdl:definitions name="SendInArtistProposal" targetNamespace="http://oracle.com/sca/soapservice/SendInArtistProposal/SendInArtistProposal/SendInArtistProposal" xmlns:tns="http://oracle.com/sca/soapservice/SendInArtistProposal/SendInArtistProposal/SendInArtistProposal" xmlns:inp1="valencia.insight.demo" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="valencia.insight.demo" schemaLocation="../Schemas/ProposeArtistService.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part1" element="inp1:proposal"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="part1" element="inp1:proposalResponse"/>
    </wsdl:message>
    <wsdl:portType name="SendInArtistProposalService">
        <wsdl:operation name="sendInProposal">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="SendInArtistProposalServiceSOAP11Binding" type="tns:SendInArtistProposalService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="sendInProposal">
            <soap:operation style="document"
                            soapAction="http://oracle.com/sca/soapservice/SendInArtistProposal/SendInArtistProposal/SendInArtistProposal/sendInProposal"/>
            <wsdl:input>
                <soap:body use="literal" parts="part1"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="part1"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>